name: NormalTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:    
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-latest, macos-latest]
        #exclude:
        #  - os: macos-latest
        #    cc: clang

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      env:
        CC: ${{ matrix.cc }}
    - name: config cmake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: test base
      working-directory: ${{github.workspace}}/bin
      run: |
        ./empty_test
        ./base_test
        ./base_stress_test
        ./sys_platform_test
        ./zbitset_test
        ./zclock_diagnostic_test
        ./zclock_test
        ./zforeach_base_test
        ./zforeach_adv_test
        ./zforeach_mempool_test
        ./zhash_map_test
        ./zlist_ext_test
        ./zmem_pool_test
        ./zpoint_test
        ./zsingle_test
        ./zstream_test
        ./ztrace_test
        ./zsymbols_test

    - name: test malloc
      working-directory: ${{github.workspace}}/bin
      run: |
        ./malloc_test
        ./malloc_slot_test
        ./malloc_slot_stress
        ./zbuddy_test

    - name: test shm
      working-directory: ${{github.workspace}}/bin
      if: runner.os == 'Linux'
      run: |
        ./mapping_test
        ./zshm_ptr_test
        ./zshm_loader_test
        ./zshm_boot_test start
        ./zshm_boot_test resume
        ./zshm_boot_test stop
        ./zshm_boot_test start heap  
      
